// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmEveIN35H4fpZaDb1ILEeyjWvdF0iXo',
    appId: '1:121449346263:web:f3fc123cd1391863a46c92',
    messagingSenderId: '121449346263',
    projectId: 'my-karaoke-riverpod',
    authDomain: 'my-karaoke-riverpod.firebaseapp.com',
    storageBucket: 'my-karaoke-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUrXtnxP__baJOg8ehaQbbSKodPmlzAk8',
    appId: '1:262708262149:android:a6365ccab7bfc300da736c',
    messagingSenderId: '262708262149',
    projectId: 'karaoke-fb-2024',
    storageBucket: 'karaoke-fb-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE7cAFxOl_fgTfibqKMuOIWGErYD9UWa4',
    appId: '1:262708262149:ios:1f285fec82024f40da736c',
    messagingSenderId: '262708262149',
    projectId: 'karaoke-fb-2024',
    storageBucket: 'karaoke-fb-2024.appspot.com',
    androidClientId: '262708262149-3tfa0mbv04eglgqp5114sp9nibdopt26.apps.googleusercontent.com',
    iosClientId: '262708262149-2bfvf4tctpo15pt6nfjebq29nm92lbqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myKaraokeSqlRiverpodV10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQKFOw-YSM0yA9_EPioBV1XRAAkIMG7_E',
    appId: '1:121449346263:ios:65807da36875a0b2a46c92',
    messagingSenderId: '121449346263',
    projectId: 'my-karaoke-riverpod',
    storageBucket: 'my-karaoke-riverpod.appspot.com',
    androidClientId: '121449346263-hjg6195vo87okquokodm6a4g67vhktod.apps.googleusercontent.com',
    iosClientId: '121449346263-qsdknj8qbut2afadk6j25h490o44vjir.apps.googleusercontent.com',
    iosBundleId: 'com.example.myKaraokeSqlRiverpodV10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjmEveIN35H4fpZaDb1ILEeyjWvdF0iXo',
    appId: '1:121449346263:web:b9ba1785321c136da46c92',
    messagingSenderId: '121449346263',
    projectId: 'my-karaoke-riverpod',
    authDomain: 'my-karaoke-riverpod.firebaseapp.com',
    storageBucket: 'my-karaoke-riverpod.appspot.com',
  );

}